### PR TITLE
Permit to develop steampipe plugin on windows

### PR DESCRIPTION
**Pull request by Etienne-Carriere**
Move OS Specific calls to specific packages (and ignore setRlimit on Windows)

### CODE REVIEW

**Comment by Etienne-Carriere** [comment]
@kaidaguerre , it seems the workflow failed due to hard-coded source repository => could you please re-approve the build.

**Comment by kaidaguerre** [comment]
@Etienne-Carriere - are you seeing the need for this change when running on Windows Subsystem for Linux? I just ask as we do not (yet) have native Windows support)

Or is it more of a preemptive change?

**Comment by Etienne-Carriere** [comment]
@kaidaguerre , I agree that Steampipe is not available on Linux but in our company we are developping in Windows (with Goland) so I would like to have it compile properly

**Comment by kaidaguerre** [comment]
@Etienne-Carriere sorry for the delay in getting back to you. Seems reasonable, merging!

**Pull request merged**
